# Generated by Django 5.1.3 on 2024-12-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='image',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.TextField(),
        ),
    ]
