# Generated by Django 5.1.3 on 2024-12-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_pokemon_image_alter_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pokemon_images/'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
