# Generated by Django 3.1.12 on 2025-01-12 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20250106_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='id',
            new_name='num',
        ),
    ]
