# Generated by Django 3.1.12 on 2025-01-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20250112_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
