# Generated by Django 5.1.5 on 2025-01-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_pokemondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='pokemondata',
            old_name='pokemon',
            new_name='pokemon_id',
        ),
        migrations.AddField(
            model_name='pokemondata',
            name='species',
            field=models.CharField(default='Pokemon', max_length=50),
        ),
    ]
