# Generated by Django 5.1.5 on 2025-01-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_alter_pokemondata_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemondata',
            name='ability',
            field=models.CharField(max_length=200),
        ),
    ]
