# Generated by Django 5.1.5 on 2025-01-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_alter_pokemondata_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemondata',
            name='ability',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pokemondata',
            name='bio',
            field=models.CharField(default='Nice Pokemon', max_length=300),
        ),
        migrations.AlterField(
            model_name='pokemondata',
            name='species',
            field=models.CharField(default='Blank Pokemon', max_length=50),
        ),
    ]
