# Generated by Django 5.1.5 on 2025-02-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_alter_pokemondata_ability_alter_pokemondata_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemondata',
            old_name='pokemon_id',
            new_name='pokemon',
        ),
    ]
