# Generated by Django 3.1.12 on 2025-01-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_pokemon_image_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(default='media/slowbro.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.JSONField(),
        ),
    ]
